=== TextControl/TXSamples_WPF_VB.NET/.NET-Core-6/TX Words/TX Text Control WPF Words Context Menu/Files/About.dtd
<!-- xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx	-->
<!-- file:				About.dtd												-->
<!-- description:		The DTD file that is related to the About.xml document.	-->
<!--																			-->
<!-- copyright:			Text Control GmbH										-->
<!-- version:			31.0.100.500											-->
<!-- xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx	-->


<!-- attributes -->
<!ENTITY % chm_filename.att	'chm_filename CDATA #IMPLIED'>
<!ENTITY % dynhelp_filename.att	'dynhelp_filename CDATA #IMPLIED'>
<!ENTITY % pdfbase_filename.att	'pdfbase_filename CDATA #IMPLIED'>
<!ENTITY % chm_title.att	'chm_title CDATA #IMPLIED'>
<!ENTITY % chm_helpcontext.att 'chm_helpcontext CDATA #IMPLIED'>
<!ENTITY % dynhelp_title.att	'dynhelp_title CDATA #IMPLIED'>
<!ENTITY % htm_prefix.att	'htm_prefix CDATA #IMPLIED'>
<!ENTITY % dynhelp_namespace.att 'dynhelp_namespace CDATA #IMPLIED' >
<!ENTITY % dynhelp_group.att 'dynhelp_group CDATA #IMPLIED'>
<!ENTITY % vendor.att 'vendor CDATA #IMPLIED'>
<!ENTITY % product.att 'product CDATA #IMPLIED'>
<!ENTITY % auto_seealso.att 'auto_seealso CDATA #IMPLIED'>
<!ENTITY % auto_seealso_charttext.att 'auto_seealso_charttext CDATA #IMPLIED'>

<!ENTITY % href.att	'href CDATA #IMPLIED'>
<!ENTITY % hrefext.att	'hrefext (true|image) #IMPLIED'>
<!ENTITY % src.att	'src CDATA #IMPLIED'>
<!ENTITY % cat.att	'cat CDATA #IMPLIED'>
<!ENTITY % cat2.att	'cat2 CDATA #IMPLIED'>
<!ENTITY % chart.att	'chart CDATA #IMPLIED'>
<!ENTITY % base.att 'base CDATA #IMPLIED'>       <!-- generates member list for base class in the derived class        -->
<!ENTITY % baseref.att 'baseref CDATA #IMPLIED'> <!-- generates additional links for the online help to the base class -->


<!-- TX categories: -->
<!-- cat.att  'cat (all|char|para|style|page|clip|io|undo|print|find|sel|control|field|hyper|table|img|hf|xml|tb|line|format|link|misc|obsol|lic|ic|list|zoom|stylep|server|scroll|tf|docserver|text|wpf|spell|charts|servervis|web|excep|ribbon|restrict|trackedchange|forms|comments) #IMPLIED' -->
<!-- cat2.att	'cat2 (dialog|para|tf) #IMPLIED' -->

<!ENTITY % doc.att 'doc (undoc) #IMPLIED'>
<!ENTITY % part.att 'part CDATA #IMPLIED'>
<!ENTITY % subpart.att 'subpart CDATA #IMPLIED'>
<!ENTITY % order.att	'order CDATA #IMPLIED'>
<!ENTITY % target.att	'target CDATA #IMPLIED'>
<!ENTITY % autogenerate.att 'autogenerate CDATA #IMPLIED'>
<!ENTITY % autoelement.att 'autoelement (constructor|prop_desc|meth_desc|event_desc|enum_desc|field_desc|class_info|win_mess|win_notif|c_struct) #IMPLIED'>
<!ENTITY % autolink.att	'autolink (true) #IMPLIED'>
<!ENTITY % autonamespace.att	'autonamespace (false) #IMPLIED'>
<!ENTITY % introduced.att 'introduced CDATA #IMPLIED'>
<!ENTITY % titleprefix.att	'titleprefix CDATA #IMPLIED'>



<!-- manual element (main element of complete documentation) -->
<!ELEMENT manual (manual_hl, manual_desc*, manual_part+)>
<!ATTLIST manual %chm_filename.att; %dynhelp_filename.att; %pdfbase_filename.att; %chm_title.att; %dynhelp_title.att; %htm_prefix.att; %dynhelp_group.att; %dynhelp_namespace.att; %vendor.att; %product.att; %chm_helpcontext.att; %auto_seealso.att; %auto_seealso_charttext.att; %autonamespace.att;>
<!ELEMENT manual_part (manual_part_hl, manual_part_desc, chap*)>
<!ATTLIST manual_part %part.att; %subpart.att;>


<!-- chapter element -->
<!ELEMENT chap (chap_hl, (chap_desc | image)*, (article | class_info | constructor | cat_list | meth_desc | prop_desc | event_desc | enum_desc | field_desc | win_mess | win_notif | c_struct)*)>
<!ATTLIST chap %part.att; %subpart.att; %order.att; %cat.att; %cat2.att; %doc.att; %autonamespace.att; %titleprefix.att; %product.att;>


<!-- main sub elements of chap element (subchapters) -->
<!ELEMENT article (ref_hl, (ref_desc | image | vb6_code | vb_code | cs_code | pas_code | js_code | other_code | list | member_list)+)>
<!ATTLIST article %target.att; %cat.att; %cat2.att;>

<!ELEMENT class_info (syntax, version?, category*, example?, seealso?)>
<!ATTLIST class_info %cat.att; %cat2.att; %autogenerate.att; %base.att; %baseref.att;>

<!ELEMENT constructor (ref_hl, ref_desc?, (ref_desc, syntax)+, param_list?, seealso?)>
<!ATTLIST constructor %target.att;>

<!ELEMENT cat_list (ref_hl, ref_desc?, category*)>
<!ATTLIST cat_list %cat.att; %cat2.att; %chart.att; %autogenerate.att; %introduced.att; %target.att; %product.att;>

<!ELEMENT meth_desc (ref_hl, ref_desc?, (ref_desc, syntax)+, param_list?, retval?, constants?, comments?, datatypes?, limit?, version?, example?, seealso?)>
<!ATTLIST meth_desc %cat.att; %cat2.att; %doc.att; %target.att;>

<!ELEMENT prop_desc (ref_hl, ref_desc, syntax, param_list?, member_list?, constants?, comments?, datatypes?, limit?,version?, example?, seealso?)>
<!ATTLIST prop_desc %cat.att; %cat2.att; %doc.att; %target.att;>

<!ELEMENT event_desc (ref_hl, ref_desc, syntax, param_list?, constants?, comments?, datatypes?, version?, example?, seealso?)>
<!ATTLIST event_desc %cat.att; %doc.att; %target.att;>

<!ELEMENT enum_desc (ref_hl, ref_desc, member_list, version?, seealso?)>
<!ATTLIST enum_desc %target.att;>

<!ELEMENT field_desc (ref_hl, ref_desc, syntax)>
<!ATTLIST field_desc %target.att;>

<!ELEMENT win_mess (ref_hl, ref_desc, param_list?, retval?, comments?, param_list_aux?, example?, unicode?, version?, seealso?)>
<!ATTLIST win_mess %cat.att; %doc.att; %target.att;>

<!ELEMENT win_notif (ref_hl, ref_desc, param_list?, retval?, version?)>
<!ATTLIST win_notif %cat.att; %doc.att; %target.att;>

<!ELEMENT c_struct (ref_hl, ref_desc, syntax, param_list?, version?)>
<!ATTLIST c_struct %cat.att; %doc.att; %target.att;>


<!-- other structural elements -->
<!ELEMENT category (category_hl, member_list?)>
<!ELEMENT syntax (syntax_hl, syntax_desc)>
<!ELEMENT syntax_desc ((vb6_code|vb_code|cs_code|pas_code|js_code|other_code|code_line)+)>
<!ELEMENT vb6_code (code_line+)>
<!ELEMENT vb_code (code_line+)>
<!ELEMENT cs_code (code_line+)>
<!ELEMENT pas_code (code_line+)>
<!ELEMENT js_code (code_line+)>
<!ELEMENT other_code (code_line+)>
<!ELEMENT list (list_desc)+>

<!ELEMENT param_list (param_hl, param+)>
<!ELEMENT param_list_aux (param_hl, param+)>
<!ELEMENT param_hl (param_name_hl, param_desc_hl)>
<!ELEMENT param (param_name, param_desc)>
<!ELEMENT param_desc (param_text+, value_list*)>

<!ELEMENT member_list (member_hl, member+)>
<!ELEMENT member_hl (member_name_hl, member_desc_hl)>
<!ELEMENT member (member_name, member_desc)>
<!ATTLIST member %autoelement.att;>

<!ELEMENT retval (retval_hl, retval_desc)>
<!ELEMENT retval_desc (retval_text+, value_list*)>

<!ELEMENT comments (comments_hl, comments_desc)>
<!ELEMENT comments_desc (comments_text+, value_list*)>

<!ELEMENT constants (constants_hl, constants_desc)>
<!ELEMENT constants_desc (constants_text, param_list)+>

<!ELEMENT datatypes (datatypes_hl, datatypes_desc)>
<!ELEMENT datatypes_desc (datatypes_text|datatypes_list)>
<!ELEMENT datatypes_list (member+)>

<!ELEMENT value_list (value_hl, value+)>
<!ELEMENT value_hl (value_name_hl, value_desc_hl)>
<!ELEMENT value (value_name, value_desc)>

<!ELEMENT example (example_hl, example_desc)>

<!ELEMENT example_desc (example_text, (vb6_code|vb_code|cs_code|pas_code|js_code|other_code|code_line)*)>

<!ELEMENT unicode (unicode_hl, unicode_desc)>

<!ELEMENT limit (limit_hl, limit_desc)>
<!ELEMENT limit_desc (limit_text+)>

<!ELEMENT version (version_hl, version_desc)>
<!ELEMENT version_desc (version_text)>

<!ELEMENT seealso (seealso_hl, seealso_desc)>


<!-- text elements -->
<!ELEMENT manual_hl (#PCDATA)>
<!ELEMENT manual_desc (#PCDATA | link | filename | foldername | apiname | uiname | list)*>
<!ELEMENT manual_part_hl (#PCDATA)>
<!ELEMENT manual_part_desc (#PCDATA)>
<!ELEMENT chap_hl (#PCDATA)>
<!ELEMENT chap_desc (#PCDATA | link | filename | foldername | apiname | uiname | list)*>
<!ELEMENT category_hl (#PCDATA)>
<!ELEMENT ref_hl (#PCDATA)>
<!ELEMENT ref_desc (#PCDATA | link | filename | foldername | apiname | uiname)*>
<!ELEMENT syntax_hl (#PCDATA)>
<!ELEMENT param_name_hl (#PCDATA)>
<!ELEMENT param_desc_hl (#PCDATA)>
<!ELEMENT param_name (#PCDATA | link)*>
<!ELEMENT param_text (#PCDATA | link | apiname | uiname)*>
<!ELEMENT member_name_hl (#PCDATA)>
<!ELEMENT member_desc_hl (#PCDATA)>
<!ELEMENT member_name (#PCDATA | link)*>
<!ATTLIST member_name %href.att; %autolink.att;>
<!ELEMENT member_desc (#PCDATA | link | filename | foldername | apiname | uiname | list)*>
<!ELEMENT retval_hl (#PCDATA)>
<!ELEMENT retval_text (#PCDATA | link | apiname)*>
<!ELEMENT comments_hl (#PCDATA)>
<!ELEMENT comments_text (#PCDATA | link | apiname | uiname)*>
<!ELEMENT constants_hl (#PCDATA)>
<!ELEMENT constants_text (#PCDATA)>
<!ELEMENT datatypes_hl (#PCDATA)>
<!ELEMENT datatypes_text (#PCDATA | link)*>
<!ELEMENT example_hl (#PCDATA)>
<!ELEMENT example_text (#PCDATA | link | apiname)*>
<!ELEMENT code_line (#PCDATA | link)*>
<!ELEMENT unicode_hl (#PCDATA)>
<!ELEMENT unicode_desc (#PCDATA | link)*>
<!ELEMENT limit_hl (#PCDATA)>
<!ELEMENT limit_text (#PCDATA | link | apiname)*>
<!ELEMENT version_hl (#PCDATA)>
<!ELEMENT version_text (#PCDATA)>
<!ELEMENT seealso_hl (#PCDATA)>
<!ELEMENT seealso_desc (#PCDATA | link)*>
<!ELEMENT value_name_hl (#PCDATA)>
<!ELEMENT value_desc_hl (#PCDATA)>
<!ELEMENT value_name (#PCDATA)>
<!ELEMENT value_desc (#PCDATA | link | apiname | uiname)*>
<!ELEMENT image (#PCDATA)>
<!ATTLIST image %src.att;>
<!ELEMENT list_desc (#PCDATA | link | filename | foldername | apiname | uiname)*>

<!-- inline text elements -->
<!ELEMENT link (#PCDATA)>
<!ATTLIST link	%href.att; %hrefext.att;>
<!ELEMENT filename (#PCDATA)>
<!ELEMENT foldername (#PCDATA)>
<!ELEMENT uiname (#PCDATA)>
<!ELEMENT apiname (#PCDATA)>

=== TextControl/TXSamples_WPF_VB.NET/.NET-Framework-48/TX Words/TX Text Control WPF Words User Access/Files/About.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/css" href="about.css"?>
<!DOCTYPE chap SYSTEM "about.dtd"[]>
<chap>
  <chap_hl>This User Access Sample</chap_hl>
  <chap_desc>In many cases, it is necessary to give user specific access to or information about the content of a document. This sample application shows an approach to assign such a user and gives examples where user access plays a role in document editing.</chap_desc>
  <chap_desc />
  <article>
    <ref_hl>Using this Sample</ref_hl>
    <ref_desc>By running this sample a document is loaded that is mostly write-protected. But one part is marked and highlighted as editable. This region can be modified by every user that opens the document.</ref_desc>
    <ref_desc />
    <ref_desc>Besides such common access, the creator of a document can assign user specific access as follows:</ref_desc>
    <ref_desc>1. Deactivate the write protection by untoggling the <apiname>Enforce Protection</apiname> button and entering <foldername>123</foldername> into the password dialog box.</ref_desc>
    <ref_desc>2. Go to the <apiname>Mark Exceptions and set Users</apiname> group and click the <apiname>Add Users</apiname> button to open the <apiname>Add Users</apiname> dialog. Enter the name in the <apiname>New User</apiname> text box with which you are logged in to the computer, press the <apiname>Add</apiname> button and leave the dialog by clicking <apiname>OK</apiname>.</ref_desc>
    <ref_desc>3. Select some text of the document and check the check box of the newly added user.</ref_desc>
    <ref_desc>4. Toggle the <apiname>Enforce Protection</apiname> button, enter a password and click <apiname>OK</apiname> to make the document write-protected again.</ref_desc>
    <ref_desc />
    <ref_desc>As you can see, only that region is still highlighted that can be changed by every user. To give access to the previously added user, go to the application menu, click on <apiname>Sign In</apiname> and create an account. </ref_desc>
    <ref_desc>Now you are logged in with the name of the added user. The previously marked regions are now highlighted and can be modified.</ref_desc>
    <ref_desc />
    <ref_desc>With the implemented user access, also added comments are assigned to the current logged in user:</ref_desc>
    <ref_desc>1. Deactivate the write protection of the document.</ref_desc>
    <ref_desc>2. Go to the <apiname>Proofing</apiname> tab, select some text, click on <apiname>Add Comment</apiname> and enter some text into the popped up comments text box. The added comment with a reference to the logged in user is shown in the <apiname>Comments</apiname> sidebar.</ref_desc>
    <ref_desc />
    <ref_desc>Same with tracked changes:</ref_desc>
    <ref_desc>1. Click on the <apiname>Tracked Changes...</apiname> split button to activate the <apiname>Tracked Changes</apiname> sidebar.</ref_desc>
    <ref_desc>2. Activate tracking changes by toggling the <apiname>Track Changes</apiname> button.</ref_desc>
    <ref_desc>3. Type, delete or replace some text in the document. The created tracked change is displayed with a reference to the logged in user in the sidebar.</ref_desc>
    <ref_desc />
  </article>
  <article>
    <ref_hl>The Code Behind</ref_hl>
    <ref_desc>The user name that should be set as current user of the <apiname>TextControl</apiname> is provided by a password dialog when handling the <apiname>Click</apiname> event of the application menu's <apiname>Sign In</apiname> button. It is set as single string array argument to the <link href="https://docs.textcontrol.com/textcontrol/wpf/ref.txtextcontrol.wpf.textcontrol.usernames.property.htm">TextControl.UserNames</link> property.</ref_desc>
    <vb_code>
      <code_line>Private Sub SignIn_Click(ByVal sender As Object, ByVal e As EventArgs)</code_line>
      <code_line>        ' Open the password dialog to sign in or create a user account.</code_line>
      <code_line>        Dim dlgUserAccessDialog As UserAccessDialog = If(m_uiCurrentUser Is Nothing, New UserAccessDialog(m_strUserName), New UserAccessDialog(m_uiCurrentUser))</code_line>
      <code_line>        If dlgUserAccessDialog.ShowDialog().Value Then</code_line>
      <code_line>                ' Get the UserInfo instance that represents the current signed in user.</code_line>
      <code_line>                m_uiCurrentUser = dlgUserAccessDialog.UserInfo</code_line>
      <code_line />
      <code_line>                ' Give the user access to the TextControl.</code_line>
      <code_line>                Me.m_txTextControl.UserNames = New String() {m_uiCurrentUser.Name}</code_line>
      <code_line />
      <code_line>                ' Hide the Sign In button.</code_line>
      <code_line>                Me.m_rmiSignIn.IsEnabled = False</code_line>
      <code_line>                Me.m_rmiSignIn.Visibility = Visibility.Collapsed</code_line>
      <code_line />
      <code_line>                ' Show the [Current User] button.</code_line>
      <code_line>                Me.m_rmbtnCurrentUser.IsEnabled = True</code_line>
      <code_line>                Me.m_rmbtnCurrentUser.Visibility = Visibility.Visible</code_line>
      <code_line />
      <code_line>                ' Save the settings of the current user.</code_line>
      <code_line>                SaveKnownUserSettings()</code_line>
      <code_line>        End If</code_line>
      <code_line>End Sub</code_line>
    </vb_code>
    <ref_desc />
    <ref_desc>The password dialog itself can be used to handle creating, editing or deleting the user access. The information about the user is stored as a <apiname>Settings</apiname> property value when the application is closed.</ref_desc>
    <vb_code>
      <code_line>Private Sub SaveKnownUserSettings()</code_line>
      <code_line>        ' Save the know users to the My.Settings.Default.KnownUsers property</code_line>
      <code_line>        My.Settings.Default.KnownUser = m_uiCurrentUser</code_line>
      <code_line>        Call My.Settings.Default.Save()</code_line>
      <code_line>End Sub</code_line>
    </vb_code>
    <ref_desc />
  </article>
  <article>
    <ref_hl>Support</ref_hl>
    <ref_desc>The <apiname>Text Control Support</apiname> section offers links to all technical resources related to <apiname>Text Control</apiname>, including documentation, getting started guides, FAQs and links to interesting blog articles.</ref_desc>
    <ref_desc>Contact us:</ref_desc>
    <ref_desc>
      <link href="https://www.textcontrol.com/support/overview/">https://www.textcontrol.com/support/overview/</link>
    </ref_desc>
    <ref_desc />
    <ref_desc />
  </article>
</chap>

=== TextControl/TXSamples_WPF_VB.NET/.NET-Core-6/TX Words/TX Text Control WPF Words Conditional Instructions/Files/About.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/css" href="about.css"?>
<!DOCTYPE chap SYSTEM "about.dtd"[]>
<chap>
  <chap_hl>This Conditional Instructions Sample</chap_hl>
  <chap_desc>In context with the ability to create forms, <apiname>TX Text Control</apiname> also provides the option to apply a specific behavior to form fields when one or more events occur. The sample illustrates the concept of such conditional instructions by deploying and previewing a form where the layout and behavior depends on predefined conditions.</chap_desc>
  <chap_desc />
  <article>
    <ref_hl>Using this Sample</ref_hl>
    <ref_desc>By running this sample, a form is loaded that already contains conditional instructions that are listed in the overview of the <apiname>Conditional Instructions</apiname> sidebar. Each entry represents a set of actions to be performed when one or more conditions are fulfilled.</ref_desc>
    <ref_desc>In order to deploy such a form, the content must be protected. This can be done by toggling both the Permissions tab's <apiname>Fill in Form Fields</apiname> and <apiname>Read Only</apiname> button before clicking <apiname>Enforce Protection</apiname>.</ref_desc>
    <ref_desc>To preview the conditional instructions of a form, the sample provides a <apiname>Preview</apiname> button inside the <apiname>Form Fields</apiname> tab that is only enabled in case the <apiname>Enabled Form Validation</apiname> button is toggled. When clicking this button, the document becomes write-protected with the previous mentioned permissions settings. When untoggling the button, the content is reset to the state that was displayed before previewing the conditional instructions behavior.</ref_desc>
    <ref_desc>On performing the preview mode, you can check the form behavior that is also described next to each form field. To show whether the defined form field content is valid, the <apiname>Highlight Invalid Values</apiname> button can be toggled.</ref_desc>
    <ref_desc>To get an insight of creating conditional instructions, check out the article <link href="https://docs.textcontrol.com/textcontrol/wpf/article.techarticle.conditionalinstructionscreate.htm">Creating and Applying Conditional Instructions</link>, that explains how to create the sample form.</ref_desc>
    <ref_desc>Other articles on that subject are:</ref_desc>
    <list>
      <list_desc>
        <link href="https://docs.textcontrol.com/textcontrol/wpf/article.techarticle.howtocreateconditionscheckformfields.htm">How-to: Creating Conditions for Check Form Fields</link>
      </list_desc>
      <list_desc>
        <link href="https://docs.textcontrol.com/textcontrol/wpf/article.techarticle.howtocreateconditionstextselectionformfields.htm">How-to: Creating Conditions for Text and Selection Form Fields</link>
      </list_desc>
      <list_desc>
        <link href="https://docs.textcontrol.com/textcontrol/wpf/article.techarticle.howtocreateconditionsdateformfields.htm">How-to: Creating Conditions for Date Form Fields</link>
      </list_desc>
      <list_desc>
        <link href="https://docs.textcontrol.com/textcontrol/wpf/article.techarticle.howtocreateinstructions.htm">How-to: Creating Instructions</link>
      </list_desc>
      <list_desc>
        <link href="https://docs.textcontrol.com/textcontrol/wpf/article.techarticle.howtocreateradiobuttongroup.htm">How-to: Creating a Radio Button Group</link>
      </list_desc>
    </list>
    <ref_desc />
  </article>
  <article>
    <ref_hl>The Code Behind</ref_hl>
    <ref_desc>To implement the preview behavior, it is necessary to store the current content and document permission settings before activating the preview mode. The content is saved to a byte array by using the <link href="https://docs.textcontrol.com/textcontrol/wpf/ref.txtextcontrol.wpf.textcontrol.save.method.htm">TextControl.Save</link> method. The <link href="https://docs.textcontrol.com/textcontrol/wpf/ref.txtextcontrol.documentpermissions.alloweditingformfields.property.htm">DocumentPermissions.AllowEditingFormFields</link> and <link href="https://docs.textcontrol.com/textcontrol/wpf/ref.txtextcontrol.documentpermissions.readonly.property.htm">DocumentPermissions.ReadOnly</link> property values are stored to temporary bool variables. </ref_desc>
    <ref_desc>To activate the preview, both document permissions variables are set to <apiname>true</apiname> and the <link href="https://docs.textcontrol.com/textcontrol/wpf/ref.txtextcontrol.wpf.textcontrol.editmode.property.htm">TextControl.EditMode</link> to <apiname>ReadAndSelect</apiname>.</ref_desc>
    <vb_code>
      <code_line>Private Sub ActivateCIPreview()</code_line>
      <code_line>        ' Store the current TextControl content.</code_line>
      <code_line>        Me.m_txTextControl.Save(m_rbtTextControlContent, BinaryStreamType.InternalUnicodeFormat)</code_line>
      <code_line />
      <code_line>        ' Store the current DocumentPermissions.AllowEditingFormFields and .ReadOnly property values.</code_line>
      <code_line>        m_bAllowEditinFormFieldsTemp = Me.m_txTextControl.DocumentPermissions.AllowEditingFormFields</code_line>
      <code_line>        m_bReadOnlyTemp = m_txTextControl.DocumentPermissions.ReadOnly</code_line>
      <code_line />
      <code_line>        ' Set those document permissions that are necessary to show a preview.</code_line>
      <code_line>        Me.m_txTextControl.DocumentPermissions.AllowEditingFormFields = True</code_line>
      <code_line>        Me.m_txTextControl.DocumentPermissions.ReadOnly = True</code_line>
      <code_line />
      <code_line>        ' Hide all ribbon groups behind the TXITEM_FormValidationGroup group</code_line>
      <code_line>        For i As Integer = 3 To Me.m_rtRibbonFormFieldsTab.Items.Count - 1</code_line>
      <code_line>                TryCast(Me.m_rtRibbonFormFieldsTab.Items(i), RibbonGroup).Visibility = Windows.Visibility.Collapsed</code_line>
      <code_line>        Next</code_line>
      <code_line />
      <code_line>        ' Activate the preview by setting the TextControl.EditMode property value to</code_line>
      <code_line>        ' EditMode.ReadAndSelect.</code_line>
      <code_line>        m_bIsPreviewActivated = True</code_line>
      <code_line>        Me.m_txTextControl.EditMode = EditMode.ReadAndSelect</code_line>
      <code_line />
      <code_line>        ' Disable the TXITEM_EnableFormValidation ribbon toggle button</code_line>
      <code_line>        m_rbtnEnableFormValidation.IsEnabled = False</code_line>
      <code_line>End Sub</code_line>
    </vb_code>
    <ref_desc />
    <ref_desc>When deactivating the preview, the saved content is reloaded by using the <link href="https://docs.textcontrol.com/textcontrol/wpf/ref.txtextcontrol.wpf.textcontrol.load.method.htm">TextControl.Load</link> method and the document permissions are reset to the values. An explicit resetting of the <apiname>TextControl.EditMode</apiname> property value to <apiname>Edit</apiname> is not necessary, because it is already set by loading the old content.</ref_desc>
    <vb_code>
      <code_line>Private Sub DeactivateCIPreview(ByVal reloadContent As Boolean)</code_line>
      <code_line>        ' Reset the preview button checked state</code_line>
      <code_line>        m_rtbtnPreviewConditionalInstructions.IsChecked = False</code_line>
      <code_line>        m_bIsPreviewActivated = False</code_line>
      <code_line />
      <code_line>        '  Enable the "Enable Form Validation" button.</code_line>
      <code_line>        m_rbtnEnableFormValidation.IsEnabled = True</code_line>
      <code_line />
      <code_line>        ' Reset the Textcontrol content and permissions.</code_line>
      <code_line>        If reloadContent Then</code_line>
      <code_line>                ' Reload the Textcontrol content.</code_line>
      <code_line>                Me.m_txTextControl.Load(m_rbtTextControlContent, BinaryStreamType.InternalUnicodeFormat)</code_line>
      <code_line>                m_rbtTextControlContent = Nothing</code_line>
      <code_line />
      <code_line>                ' Reset the DocumentPermissions.AllowEditingFormFields property value and .ReadOnly property values.</code_line>
      <code_line>                Me.m_txTextControl.DocumentPermissions.AllowEditingFormFields = m_bAllowEditinFormFieldsTemp</code_line>
      <code_line>                Me.m_txTextControl.DocumentPermissions.ReadOnly = m_bReadOnlyTemp</code_line>
      <code_line>        End If</code_line>
      <code_line>End Sub</code_line>
    </vb_code>
    <ref_desc />
  </article>
  <article>
    <ref_hl>Support</ref_hl>
    <ref_desc>The <apiname>Text Control Support</apiname> offers links to all technical resources related to <apiname>Text Control</apiname>, including documentation, getting started guides, FAQs and links to interesting blog articles.</ref_desc>
    <ref_desc>Contact us under:</ref_desc>
    <ref_desc>
      <link href="https://www.textcontrol.com/support/overview/">https://www.textcontrol.com/support/overview/</link>
    </ref_desc>
    <ref_desc />
    <ref_desc />
  </article>
</chap>
