=== TextControl/TXSamples_WPF_VB.NET/.NET-Core-6/TX Words/TX Text Control WPF Words Context Menu/Files/About.dtd
<!-- xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx	-->
<!-- file:				About.dtd												-->
<!-- description:		The DTD file that is related to the About.xml document.	-->
<!--																			-->
<!-- copyright:			Text Control GmbH										-->
<!-- version:			31.0.100.500											-->
<!-- xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx	-->


<!-- attributes -->
<!ENTITY % chm_filename.att	'chm_filename CDATA #IMPLIED'>
<!ENTITY % dynhelp_filename.att	'dynhelp_filename CDATA #IMPLIED'>
<!ENTITY % pdfbase_filename.att	'pdfbase_filename CDATA #IMPLIED'>
<!ENTITY % chm_title.att	'chm_title CDATA #IMPLIED'>
<!ENTITY % chm_helpcontext.att 'chm_helpcontext CDATA #IMPLIED'>
<!ENTITY % dynhelp_title.att	'dynhelp_title CDATA #IMPLIED'>
<!ENTITY % htm_prefix.att	'htm_prefix CDATA #IMPLIED'>
<!ENTITY % dynhelp_namespace.att 'dynhelp_namespace CDATA #IMPLIED' >
<!ENTITY % dynhelp_group.att 'dynhelp_group CDATA #IMPLIED'>
<!ENTITY % vendor.att 'vendor CDATA #IMPLIED'>
<!ENTITY % product.att 'product CDATA #IMPLIED'>
<!ENTITY % auto_seealso.att 'auto_seealso CDATA #IMPLIED'>
<!ENTITY % auto_seealso_charttext.att 'auto_seealso_charttext CDATA #IMPLIED'>

<!ENTITY % href.att	'href CDATA #IMPLIED'>
<!ENTITY % hrefext.att	'hrefext (true|image) #IMPLIED'>
<!ENTITY % src.att	'src CDATA #IMPLIED'>
<!ENTITY % cat.att	'cat CDATA #IMPLIED'>
<!ENTITY % cat2.att	'cat2 CDATA #IMPLIED'>
<!ENTITY % chart.att	'chart CDATA #IMPLIED'>
<!ENTITY % base.att 'base CDATA #IMPLIED'>       <!-- generates member list for base class in the derived class        -->
<!ENTITY % baseref.att 'baseref CDATA #IMPLIED'> <!-- generates additional links for the online help to the base class -->


<!-- TX categories: -->
<!-- cat.att  'cat (all|char|para|style|page|clip|io|undo|print|find|sel|control|field|hyper|table|img|hf|xml|tb|line|format|link|misc|obsol|lic|ic|list|zoom|stylep|server|scroll|tf|docserver|text|wpf|spell|charts|servervis|web|excep|ribbon|restrict|trackedchange|forms|comments) #IMPLIED' -->
<!-- cat2.att	'cat2 (dialog|para|tf) #IMPLIED' -->

<!ENTITY % doc.att 'doc (undoc) #IMPLIED'>
<!ENTITY % part.att 'part CDATA #IMPLIED'>
<!ENTITY % subpart.att 'subpart CDATA #IMPLIED'>
<!ENTITY % order.att	'order CDATA #IMPLIED'>
<!ENTITY % target.att	'target CDATA #IMPLIED'>
<!ENTITY % autogenerate.att 'autogenerate CDATA #IMPLIED'>
<!ENTITY % autoelement.att 'autoelement (constructor|prop_desc|meth_desc|event_desc|enum_desc|field_desc|class_info|win_mess|win_notif|c_struct) #IMPLIED'>
<!ENTITY % autolink.att	'autolink (true) #IMPLIED'>
<!ENTITY % autonamespace.att	'autonamespace (false) #IMPLIED'>
<!ENTITY % introduced.att 'introduced CDATA #IMPLIED'>
<!ENTITY % titleprefix.att	'titleprefix CDATA #IMPLIED'>



<!-- manual element (main element of complete documentation) -->
<!ELEMENT manual (manual_hl, manual_desc*, manual_part+)>
<!ATTLIST manual %chm_filename.att; %dynhelp_filename.att; %pdfbase_filename.att; %chm_title.att; %dynhelp_title.att; %htm_prefix.att; %dynhelp_group.att; %dynhelp_namespace.att; %vendor.att; %product.att; %chm_helpcontext.att; %auto_seealso.att; %auto_seealso_charttext.att; %autonamespace.att;>
<!ELEMENT manual_part (manual_part_hl, manual_part_desc, chap*)>
<!ATTLIST manual_part %part.att; %subpart.att;>


<!-- chapter element -->
<!ELEMENT chap (chap_hl, (chap_desc | image)*, (article | class_info | constructor | cat_list | meth_desc | prop_desc | event_desc | enum_desc | field_desc | win_mess | win_notif | c_struct)*)>
<!ATTLIST chap %part.att; %subpart.att; %order.att; %cat.att; %cat2.att; %doc.att; %autonamespace.att; %titleprefix.att; %product.att;>


<!-- main sub elements of chap element (subchapters) -->
<!ELEMENT article (ref_hl, (ref_desc | image | vb6_code | vb_code | cs_code | pas_code | js_code | other_code | list | member_list)+)>
<!ATTLIST article %target.att; %cat.att; %cat2.att;>

<!ELEMENT class_info (syntax, version?, category*, example?, seealso?)>
<!ATTLIST class_info %cat.att; %cat2.att; %autogenerate.att; %base.att; %baseref.att;>

<!ELEMENT constructor (ref_hl, ref_desc?, (ref_desc, syntax)+, param_list?, seealso?)>
<!ATTLIST constructor %target.att;>

<!ELEMENT cat_list (ref_hl, ref_desc?, category*)>
<!ATTLIST cat_list %cat.att; %cat2.att; %chart.att; %autogenerate.att; %introduced.att; %target.att; %product.att;>

<!ELEMENT meth_desc (ref_hl, ref_desc?, (ref_desc, syntax)+, param_list?, retval?, constants?, comments?, datatypes?, limit?, version?, example?, seealso?)>
<!ATTLIST meth_desc %cat.att; %cat2.att; %doc.att; %target.att;>

<!ELEMENT prop_desc (ref_hl, ref_desc, syntax, param_list?, member_list?, constants?, comments?, datatypes?, limit?,version?, example?, seealso?)>
<!ATTLIST prop_desc %cat.att; %cat2.att; %doc.att; %target.att;>

<!ELEMENT event_desc (ref_hl, ref_desc, syntax, param_list?, constants?, comments?, datatypes?, version?, example?, seealso?)>
<!ATTLIST event_desc %cat.att; %doc.att; %target.att;>

<!ELEMENT enum_desc (ref_hl, ref_desc, member_list, version?, seealso?)>
<!ATTLIST enum_desc %target.att;>

<!ELEMENT field_desc (ref_hl, ref_desc, syntax)>
<!ATTLIST field_desc %target.att;>

<!ELEMENT win_mess (ref_hl, ref_desc, param_list?, retval?, comments?, param_list_aux?, example?, unicode?, version?, seealso?)>
<!ATTLIST win_mess %cat.att; %doc.att; %target.att;>

<!ELEMENT win_notif (ref_hl, ref_desc, param_list?, retval?, version?)>
<!ATTLIST win_notif %cat.att; %doc.att; %target.att;>

<!ELEMENT c_struct (ref_hl, ref_desc, syntax, param_list?, version?)>
<!ATTLIST c_struct %cat.att; %doc.att; %target.att;>


<!-- other structural elements -->
<!ELEMENT category (category_hl, member_list?)>
<!ELEMENT syntax (syntax_hl, syntax_desc)>
<!ELEMENT syntax_desc ((vb6_code|vb_code|cs_code|pas_code|js_code|other_code|code_line)+)>
<!ELEMENT vb6_code (code_line+)>
<!ELEMENT vb_code (code_line+)>
<!ELEMENT cs_code (code_line+)>
<!ELEMENT pas_code (code_line+)>
<!ELEMENT js_code (code_line+)>
<!ELEMENT other_code (code_line+)>
<!ELEMENT list (list_desc)+>

<!ELEMENT param_list (param_hl, param+)>
<!ELEMENT param_list_aux (param_hl, param+)>
<!ELEMENT param_hl (param_name_hl, param_desc_hl)>
<!ELEMENT param (param_name, param_desc)>
<!ELEMENT param_desc (param_text+, value_list*)>

<!ELEMENT member_list (member_hl, member+)>
<!ELEMENT member_hl (member_name_hl, member_desc_hl)>
<!ELEMENT member (member_name, member_desc)>
<!ATTLIST member %autoelement.att;>

<!ELEMENT retval (retval_hl, retval_desc)>
<!ELEMENT retval_desc (retval_text+, value_list*)>

<!ELEMENT comments (comments_hl, comments_desc)>
<!ELEMENT comments_desc (comments_text+, value_list*)>

<!ELEMENT constants (constants_hl, constants_desc)>
<!ELEMENT constants_desc (constants_text, param_list)+>

<!ELEMENT datatypes (datatypes_hl, datatypes_desc)>
<!ELEMENT datatypes_desc (datatypes_text|datatypes_list)>
<!ELEMENT datatypes_list (member+)>

<!ELEMENT value_list (value_hl, value+)>
<!ELEMENT value_hl (value_name_hl, value_desc_hl)>
<!ELEMENT value (value_name, value_desc)>

<!ELEMENT example (example_hl, example_desc)>

<!ELEMENT example_desc (example_text, (vb6_code|vb_code|cs_code|pas_code|js_code|other_code|code_line)*)>

<!ELEMENT unicode (unicode_hl, unicode_desc)>

<!ELEMENT limit (limit_hl, limit_desc)>
<!ELEMENT limit_desc (limit_text+)>

<!ELEMENT version (version_hl, version_desc)>
<!ELEMENT version_desc (version_text)>

<!ELEMENT seealso (seealso_hl, seealso_desc)>


<!-- text elements -->
<!ELEMENT manual_hl (#PCDATA)>
<!ELEMENT manual_desc (#PCDATA | link | filename | foldername | apiname | uiname | list)*>
<!ELEMENT manual_part_hl (#PCDATA)>
<!ELEMENT manual_part_desc (#PCDATA)>
<!ELEMENT chap_hl (#PCDATA)>
<!ELEMENT chap_desc (#PCDATA | link | filename | foldername | apiname | uiname | list)*>
<!ELEMENT category_hl (#PCDATA)>
<!ELEMENT ref_hl (#PCDATA)>
<!ELEMENT ref_desc (#PCDATA | link | filename | foldername | apiname | uiname)*>
<!ELEMENT syntax_hl (#PCDATA)>
<!ELEMENT param_name_hl (#PCDATA)>
<!ELEMENT param_desc_hl (#PCDATA)>
<!ELEMENT param_name (#PCDATA | link)*>
<!ELEMENT param_text (#PCDATA | link | apiname | uiname)*>
<!ELEMENT member_name_hl (#PCDATA)>
<!ELEMENT member_desc_hl (#PCDATA)>
<!ELEMENT member_name (#PCDATA | link)*>
<!ATTLIST member_name %href.att; %autolink.att;>
<!ELEMENT member_desc (#PCDATA | link | filename | foldername | apiname | uiname | list)*>
<!ELEMENT retval_hl (#PCDATA)>
<!ELEMENT retval_text (#PCDATA | link | apiname)*>
<!ELEMENT comments_hl (#PCDATA)>
<!ELEMENT comments_text (#PCDATA | link | apiname | uiname)*>
<!ELEMENT constants_hl (#PCDATA)>
<!ELEMENT constants_text (#PCDATA)>
<!ELEMENT datatypes_hl (#PCDATA)>
<!ELEMENT datatypes_text (#PCDATA | link)*>
<!ELEMENT example_hl (#PCDATA)>
<!ELEMENT example_text (#PCDATA | link | apiname)*>
<!ELEMENT code_line (#PCDATA | link)*>
<!ELEMENT unicode_hl (#PCDATA)>
<!ELEMENT unicode_desc (#PCDATA | link)*>
<!ELEMENT limit_hl (#PCDATA)>
<!ELEMENT limit_text (#PCDATA | link | apiname)*>
<!ELEMENT version_hl (#PCDATA)>
<!ELEMENT version_text (#PCDATA)>
<!ELEMENT seealso_hl (#PCDATA)>
<!ELEMENT seealso_desc (#PCDATA | link)*>
<!ELEMENT value_name_hl (#PCDATA)>
<!ELEMENT value_desc_hl (#PCDATA)>
<!ELEMENT value_name (#PCDATA)>
<!ELEMENT value_desc (#PCDATA | link | apiname | uiname)*>
<!ELEMENT image (#PCDATA)>
<!ATTLIST image %src.att;>
<!ELEMENT list_desc (#PCDATA | link | filename | foldername | apiname | uiname)*>

<!-- inline text elements -->
<!ELEMENT link (#PCDATA)>
<!ATTLIST link	%href.att; %hrefext.att;>
<!ELEMENT filename (#PCDATA)>
<!ELEMENT foldername (#PCDATA)>
<!ELEMENT uiname (#PCDATA)>
<!ELEMENT apiname (#PCDATA)>

=== TextControl/TXSamples_WPF_VB.NET/.NET-Framework-48/TX Words/TX Text Control WPF Words Reporting/Files/About.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/css" href="about.css"?>
<!DOCTYPE chap SYSTEM "about.dtd"[]>
<chap>
  <chap_hl>This Reporting Sample</chap_hl>
  <chap_desc>Reporting and Mail Merge have become wide-sweeping terms for automated document, report and label creation. Creating invoices, proposals, generated covering letters or shipping labels was never that easy - simply using word processing skills. This sample illustrates the typical process including creating a reporting template, merging its application fields with data from various data sources and exporting the result of that process. </chap_desc>
  <chap_desc />
  <article>
    <ref_hl>Using this Sample</ref_hl>
    <ref_desc>To create a reporting template, first a data source must be chosen. That can be done by selecting such a source with the dialog that is opened when clicking the corresponding <apiname>Select Data Source</apiname> drop down menu button. In this sample an additional <apiname>Load Sample Database</apiname> button is added to the drop down menu. It provides an XML data base that can be used to create a sample reporting template.</ref_desc>
    <ref_desc>After loading a database, the <apiname>Insert Merge Field</apiname> and <apiname>Insert Merge Block</apiname> drop down menus contain merge fields and merge blocks that can be inserted into the document. These items are related to a master table that can be chosen by clicking one of the <apiname>Select Master Table</apiname> drop down menu buttons that represents such a table. The <apiname>Field Navigation</apiname> sidebar provides an overview and editing options for all inserted merge fields and merge blocks.</ref_desc>
    <ref_desc>How such a reporting template can be structured in the end, can be seen from one of the sample templates that are provided via the application menu. Each of these templates is related to the sample XML database.</ref_desc>
    <ref_desc>When finishing the design process, the template can be used for the merge process. Usually, creating a template and performing a merge process are two separate operations. In this sample, however, these two processes are combined into one sequence for reasons of comprehension.</ref_desc>
    <ref_desc>The merge process is initiated by clicking the <apiname>Merge and Export</apiname> button that opens a dialog to specify some merge settings such as determining the number of records, whether or not the resulting documents should be merged into a single document and what kind of empty merge elements should be removed.</ref_desc>
    <ref_desc>After accepting the set merge settings by clicking the <apiname>OK</apiname> button, the merge process begins.  When it is finished, the result tab and the first merged record result is displayed. The user can navigate through all created records. </ref_desc>
    <ref_desc>To export the results, the <apiname>Export Merge Result...</apiname> button can be clicked. It opens a dialog where the user can determine the prefix text, the destination directory and format of the exported files. </ref_desc>
    <ref_desc />
  </article>
  <article>
    <ref_hl>The Code Behind</ref_hl>
    <ref_desc>Both creating the template and performing the merge process are handled by an instance of the <link href="https://docs.textcontrol.com/textcontrol/wpf/ref.txtextcontrol.documentserver.datasources.datasourcemanager.class.htm">DataSourceManager</link> that is provided by the <link href="https://docs.textcontrol.com/textcontrol/wpf/ref.txtextcontrol.wpf.ribbonreportingtab.class.htm">RibbonReportingTab's</link><link href="https://docs.textcontrol.com/textcontrol/wpf/ref.txtextcontrol.wpf.ribbonreportingtab.datasourcemanager.property.htm">DataSourceManager</link> property.</ref_desc>
    <ref_desc>The sample database is loaded by using the <link href="https://docs.textcontrol.com/textcontrol/wpf/ref.txtextcontrol.documentserver.datasources.datasourcemanager.loadxmlfile.method.htm">DataSourceManager.LoadXmlFile</link> method.</ref_desc>
    <vb_code>
      <code_line>Private Sub SampleDatabaseButton_Click(ByVal sender As Object, ByVal e As RoutedEventArgs)</code_line>
      <code_line>        Me.m_rtRibbonReportingTab.DataSourceManager.LoadXmlFile(m_strFilesDirectory &amp; "sample_db.xml")</code_line>
      <code_line>End Sub</code_line>
    </vb_code>
    <ref_desc />
    <ref_desc>The merge process itself is performed by the <link href="https://docs.textcontrol.com/textcontrol/wpf/ref.txtextcontrol.documentserver.datasources.datasourcemanager.merge.method.htm">DataSourceManager.Merge</link> method and returns a list of byte arrays containing one binary <link href="https://docs.textcontrol.com/textcontrol/wpf/ref.txtextcontrol.binarystreamtype.enumeration.htm">TX internal unicode format</link> document for each merged result.</ref_desc>
    <vb_code>
      <code_line>Private Sub MergePreview(ByVal template As Byte(), ByVal maxPreviews As Integer, ByVal textControl As TextControl, ByVal msMergeSettings As MergeSettings, ByVal reportingTab As RibbonReportingTab)</code_line>
      <code_line>        Try</code_line>
      <code_line>                m_lstMergedFiles = reportingTab.DataSourceManager.Merge(template, maxPreviews, textControl, msMergeSettings)</code_line>
      <code_line>        Catch e As Exception</code_line>
      <code_line>                ' Store the exception if thrown.</code_line>
      <code_line>                m_exException = e</code_line>
      <code_line>        End Try</code_line>
      <code_line>End Sub</code_line>
    </vb_code>
    <ref_desc />
    <ref_desc>As mentioned before, usually, creating a template and performing a merge process are two separate operations. For this reason, in real-world applications, we don't recommend to use the <apiname>DataSourceManager.Merge</apiname> method for the merge process, as shown in this example. Instead, you should always use an instance of the <link href="https://docs.textcontrol.com/textcontrol/wpf/ref.txtextcontrol.documentserver.mailmerge.class.htm">MailMerge</link> class to merge template documents with database content.</ref_desc>
    <ref_desc>For more details, please visit</ref_desc>
    <ref_desc>
      <link href="https://docs.textcontrol.com/textcontrol/wpf/article.wpf.mailmerge.htm">Howto: Mail Merge</link>
    </ref_desc>
    <ref_desc />
  </article>
  <article>
    <ref_hl>Support</ref_hl>
    <ref_desc>The <apiname>Text Control Support</apiname> section offers links to all technical resources related to <apiname>Text Control</apiname>, including documentation, getting started guides, FAQs and links to interesting blog articles.</ref_desc>
    <ref_desc>Contact us:</ref_desc>
    <ref_desc>
      <link href="https://www.textcontrol.com/support/overview/">https://www.textcontrol.com/support/overview/</link>
    </ref_desc>
    <ref_desc />
  </article>
</chap>

=== TextControl/TXSamples_WPF_VB.NET/.NET-Core-6/TX Words/TX Text Control WPF Words Context Menu/Files/About.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/css" href="about.css"?>
<!DOCTYPE chap SYSTEM "about.dtd"[]>
<chap>
  <chap_hl>This Context Menu Sample</chap_hl>
  <chap_desc>When right-clicking <apiname>TextControl</apiname>, a built-in context menu appears that provides context related items. This sample shows how to extend such a <apiname>TextControl</apiname> context menu. When right-clicking a <link href="https://docs.textcontrol.com/textcontrol/wpf/ref.txtextcontrol.framebase.class.htm">frame base element</link>, an additional item is added to the context menu that opens a dialog to edit the name of that object.</chap_desc>
  <chap_desc />
  <article>
    <ref_hl>Using this Sample</ref_hl>
    <ref_desc>Insert a frame base element and right-click it. Now the default context menu appears including an additional item (<apiname>Frame Name...</apiname>). When clicking  that item, a dialog is opened to set the name of the clicked frame base element.</ref_desc>
    <ref_desc />
  </article>
  <article>
    <ref_hl>The Code Behind</ref_hl>
    <ref_desc>When right-clicking <apiname>TextControl</apiname>, a <link href="https://docs.textcontrol.com/textcontrol/wpf/ref.txtextcontrol.wpf.textcontrol.textcontextmenuopening.event.htm">TextContextMenuOpening</link> event is fired. Its handler has an <link href="https://docs.textcontrol.com/textcontrol/wpf/ref.txtextcontrol.wpf.textcontextmenueventargs.class.htm">event argument</link> that provides the shown <link href="https://docs.textcontrol.com/textcontrol/wpf/ref.txtextcontrol.wpf.textcontextmenueventargs.textcontextmenu.property.htm">context menu</link> and information about it. In this sample, when a frame base element is right-clicked, that context menu is extended by a tool strip separator and an item that opens a custom dialog to edit that object.</ref_desc>
    <vb_code>
      <code_line>Private Sub TextControl_TextContextMenuOpening(ByVal sender As Object, ByVal e As TextContextMenuEventArgs)</code_line>
      <code_line>        If (e.ContextMenuLocation And ContextMenuLocation.SelectedFrame) &lt;&gt; 0 Then</code_line>
      <code_line>                ' A frame is selected</code_line>
      <code_line>                AddFrameContextMenuItems(e.TextContextMenu)</code_line>
      <code_line>        End If</code_line>
      <code_line>End Sub</code_line>
    </vb_code>
    <ref_desc />
  </article>
  <article>
    <ref_hl>Support</ref_hl>
    <ref_desc>The <apiname>Text Control Support</apiname> section offers links to all technical resources related to <apiname>Text Control</apiname>, including documentation, getting started guides, FAQs and links to interesting blog articles.</ref_desc>
    <ref_desc>Contact us:</ref_desc>
    <ref_desc>
      <link href="https://www.textcontrol.com/support/overview/">https://www.textcontrol.com/support/overview/</link>
    </ref_desc>
    <ref_desc />
  </article>
</chap>

=== TextControl/TXSamples_WPF_VB.NET/.NET-Core-6/TX Words/TX Text Control WPF Words Right To Left/Files/About.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/css" href="about.css"?>
<!DOCTYPE chap SYSTEM "about.dtd"[]>
<chap>
  <chap_hl>This Right to Left Sample</chap_hl>
  <chap_desc>
    <apiname>Text Control</apiname> supports right to left text rendering for languages such as Arabic or Hebrew. Most often, users working with "RTL languages", also prefer an application view with a right-to-left orientation. This sample shows how to implement a button that restarts the program in the opposite application view.</chap_desc>
  <chap_desc />
  <article>
    <ref_hl>Using this Sample</ref_hl>
    <ref_desc>To change the application view, click the <apiname>Right to Left</apiname> button. It opens a message box where the user can confirm the view change by restarting the program. After the application is restarted, the orientation of the sample is changed to right to left.</ref_desc>
    <ref_desc />
  </article>
  <article>
    <ref_hl>The Code Behind</ref_hl>
    <ref_desc>When clicking the <apiname>Right to Left</apiname> button, the requested layout will be saved as <apiname>Settings</apiname> property value before the application is restarted.</ref_desc>
    <vb_code>
      <code_line>Private Sub RightToLeftFormLayout_Click(ByVal sender As Object, ByVal e As EventArgs)</code_line>
      <code_line>        Dim bIsRightToLeft As Boolean = CBool(TryCast(sender, RibbonButton).Tag)</code_line>
      <code_line>        If SaveDirtyDocumentBeforeReset(bIsRightToLeft) Then</code_line>
      <code_line>                My.Settings.Default.RightToLeft = If(bIsRightToLeft, FlowDirection.LeftToRight, FlowDirection.RightToLeft)</code_line>
      <code_line>                SaveRecentFiles()</code_line>
      <code_line>                m_bRestartApplication = True</code_line>
      <code_line>                Call Application.Current.Shutdown()</code_line>
      <code_line>        End If</code_line>
      <code_line>End Sub</code_line>
      <code_line />
      <code_line>Private Sub MainWindow_Closed(ByVal sender As Object, ByVal e As EventArgs)</code_line>
      <code_line>        If m_bRestartApplication Then</code_line>
      <code_line>                Process.Start(Application.ResourceAssembly.Location)</code_line>
      <code_line>        End If</code_line>
      <code_line>End Sub</code_line>
    </vb_code>
    <ref_desc />
    <ref_desc>After that, this layout is loaded when the application is initialized for restart.</ref_desc>
    <vb_code>
      <code_line>Public Sub New()</code_line>
      <code_line>        ' Add an unhandled exception handler</code_line>
      <code_line>        Dim currentDomain As AppDomain = AppDomain.CurrentDomain</code_line>
      <code_line>        AddHandler currentDomain.UnhandledException, AddressOf CurrentDomain_UnhandledException</code_line>
      <code_line />
      <code_line>        Me.InitializeComponent()</code_line>
      <code_line />
      <code_line>        ' Set some texts</code_line>
      <code_line>        Me.Title = My.Resources.MainWindow_Caption_Product</code_line>
      <code_line>        Me.m_rtRibbonTableLayoutTab.ContextualTabGroupHeader = My.Resources.ContextualTabGroup_TableTools</code_line>
      <code_line>        Me.m_rtRibbonFormulaTab.ContextualTabGroupHeader = My.Resources.ContextualTabGroup_TableTools</code_line>
      <code_line>        Me.m_rtRibbonFrameLayoutTab.ContextualTabGroupHeader = My.Resources.ContextualTabGroup_FrameTools</code_line>
      <code_line>        Me.m_ctgTableTools.Header = My.Resources.ContextualTabGroup_TableTools</code_line>
      <code_line>        Me.m_ctgFrameTools.Header = My.Resources.ContextualTabGroup_FrameTools</code_line>
      <code_line />
      <code_line>        ' Get and set saved application settings.</code_line>
      <code_line>        LoadRightToLeftSettings()</code_line>
      <code_line>        LoadRecentFiles()</code_line>
      <code_line>End Sub</code_line>
    </vb_code>
    <ref_desc />
    <ref_desc>It updates the <apiname>FlowDirection</apiname> property value of the application.</ref_desc>
    <vb_code>
      <code_line>Private Sub LoadRightToLeftSettings()</code_line>
      <code_line>        FlowDirection = My.Settings.Default.RightToLeft</code_line>
      <code_line>End Sub</code_line>
    </vb_code>
    <ref_desc />
  </article>
  <article>
    <ref_hl>Support</ref_hl>
    <ref_desc>The <apiname>Text Control Support</apiname> section offers links to all technical resources related to <apiname>Text Control</apiname>, including documentation, getting started guides, FAQs and links to interesting blog articles.</ref_desc>
    <ref_desc>Contact us:</ref_desc>
    <ref_desc>
      <link href="https://www.textcontrol.com/support/overview/">https://www.textcontrol.com/support/overview/</link>
    </ref_desc>
    <ref_desc />
  </article>
</chap>
