=== TextControl/TXSamples_WPF_VB.NET/.NET-Core-6/Howto/XMLBasics/Files/address.dtd
<!ELEMENT address ( address_record+ )>

<!ELEMENT address_record ( name, street?, city?, email )>

<!ELEMENT name (#PCDATA )>
<!ELEMENT street (#PCDATA )>
<!ELEMENT city (#PCDATA )>
<!ELEMENT email (#PCDATA )>

=== TextControl/TXSamples_WPF_VB.NET/.NET-Core-6/Howto/XMLBasics/Files/address.xml
<?xml version="1.0"?>
<?XML:stylesheet type="text/css" href="address.css"?>
<!DOCTYPE address SYSTEM "address.dtd">
<address>
	<address_record>
		<name>Paul</name>
		<street>Baker Street</street>
		<city>London</city>
		<email>paul@hotmail.com</email>
	</address_record>
	<address_record>
		<name>George</name>
		<email>george@hotmail.com</email>
	</address_record>
</address>
